# Generated by Django 2.2.5 on 2020-08-07 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=225)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=225)),
                ('dept', models.CharField(max_length=100)),
                ('desc', models.TextField(max_length=225)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('status', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('f_id', models.CharField(max_length=225)),
                ('desig', models.CharField(max_length=100)),
                ('dept', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=225)),
                ('phone_no', models.CharField(max_length=225)),
                ('gender', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('date_of_join', models.DateField()),
                ('total_leaves', models.IntegerField(default=11)),
                ('leaves_used', models.IntegerField(default=0)),
                ('leaves_remaining', models.IntegerField(default=11)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
