# Generated by Django 2.2.5 on 2020-08-07 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='password',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
