# Generated by Django 2.2.5 on 2020-08-07 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0002_staff_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverecord',
            name='no_of_days',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='leaverecord',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
